name: Tests
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "24.2.0"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install pipx
        run: python -m pip install --upgrade pipx
      - name: Install poetry
        run: pipx install 'poetry==1.7.1'
      - name: Install dependencies
        run: poetry install --with=dev
      - name: pytest
        run: poetry run pytest

